= Development

== Building from Source

You do not need to build from source to use Spring Data for CDO.
The dependencies are deployed to the https://central.sonatype.com/[Central Repository].

But if you want to try out the latest and greatest, Spring Data for CDO can be easily built with the regular `mvn` command,
or by using the https://github.com/apache/maven-wrapper[maven wrapper] (already included in the project).
If you want to build with the regular `mvn` command, you will need https://maven.apache.org/download.cgi[Maven v3.8.3 or above].

You also need JDK 21.
Check that the `JAVA_HOME` environment variable is pointing to the correct JDK, or use:

[source,shell]
----
# (1) Select Java 21
$ sudo update-alternatives --config java

# (2) Check
$ mvn --version
----

To build Spring Data for CDO, execute the following commands in the terminal from the root of this project:

[source,shell]
----
# (1) Get all required Eclipse dependencies first. This step needs to be run only once:
$ mvn clean validate -f ./spring-data-cdo-distribution/pom.xml -PfetchEclipseDependencies

# (2) Package and install the 'spring-data-cdo' module containing the framework
$ mvn install -DskipTests
----

The dependencies are deployed to your local Maven repository usually located at `~/.m2/`.

== Building the Reference Documentation

Building the documentation builds also the project without running tests:

[source,bash]
----
$ mvn install -DskipTests -Pdistribute
----

The generated documentation is available from `target/site/reference/html/index.html`.
The Maven profile `distribute` is provided by `spring-data-parent`.
For more information see link:https://github.com/spring-projects/spring-data-build[https://github.com/spring-projects/spring-data-build] on how to set up the AsciiDoc documentation.

== Deployment

=== Releases

The Java artifacts are deployed to the https://central.sonatype.com/[Maven Central Repository]:

[source,shell]
----
# Deploy all modules
$ mvn clean deploy -DskipTests -P release,central

# Deploy single modules
$ mvn clean deploy -DskipTests -P release,central -pl :spring-data-cdo
$ mvn clean deploy -DskipTests -P release,central -pl :spring-data-cdo-distribution
----

The staged artifacts have to be released manually.

=== Settings

- GPG signing is required for artifact publishing. Refer to the official documentation for setup instructions: https://central.sonatype.org/publish/requirements/gpg/[Sonatype GPG Requirements]. It requires the `gpg` command-line tool to be installed:

[source,shell]
----
$ sudo apt install gnupg2
----

GPG credentials must be configured in your Maven `settings.xml`.
Refer to the official guide for details: https://central.sonatype.org/publish/publish-portal-maven/#credentials[Sonatype Credential Setup].

Ensure that `settings.xml` includes:

- A `<profile>` with `<id>central</id>`
- A corresponding `<server>` entry with the same `<id>central</id>`

These configurations provide the passphrase and server authentication needed by `maven-gpg-plugin`.

- Ensure the `maven-gpg-plugin` is correctly configured with the appropriate `keyname` and `passphraseServerId`.
- To list available GPG keys with short key IDs, run:
+
----
$ gpg --list-keys --keyid-format short
[...]
pub   rsa3072/26A857F8 2024-02-07 [SC] [expires: 2026-02-06]
BAA38072FD25B089867CC85D1B40F84026A857F8
----
In this example, the `keyname` and `passphraseServerId` are both set to `0x26A857F8`.


== Code of Conduct

This project is governed by the link:CODE_OF_CONDUCT.adoc[Spring Code of Conduct].
By participating in this project, you agree to abide by its terms and uphold
a respectful and inclusive community environment.